openapi: 3.0.0
info:
  title: 'Avrillo tech test docs'
  version: '1.0.0'
paths:
  /api/token:
    post:
      tags:
        - Token
      summary: Get a new token
      description: Get a new token to use for api
      operationId: get-token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/tokenRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tokenResponse'
        422:
          description: 'Validation errors'
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: The passphrase is invalid. (and 1 more error)
                  errors:
                    type: object
                    properties:
                      passphrase:
                        type: string
                        example: The passphrase is invalid
                      secret:
                        type: string
                        example: The secret is invalid
  /api/quotes:
    get:
      tags:
        - Quotes
      summary: Get quotes
      description: Get a list of quotes
      operationId: get-quotes
      parameters:
        - $ref: '#/components/parameters/token'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quotesResponse'
        401:
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: Unauthorized
  /api/quotes/refresh:
    get:
      tags:
        - Quotes
      summary: Refresh quotes
      description: Refreshes the list of quotes
      operationId: refresh-quotes
      parameters:
        - $ref: '#/components/parameters/token'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quotesResponse'
        401:
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: Unauthorized

components:
  schemas:
    ########### Responses ##############
    tokenResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            token:
              type: string
            expires_at:
              type: string
              example: 2024-04-27 14:12:22

    quotesResponse:
      type: object
      properties:
        data:
          type: array
          items:
            type: string
          example: [ "We must form a union. We must unify", "All you have to be is yourself","There are people sleeping in parking lots","Perhaps I should have been more like water today", "I am one of the most famous people on the planet" ]

    ############ Request bodies ############
    tokenRequest:
      type: object
      properties:
        passphrase:
          type: string
          example: C275F5EF21169E1F9EEFC100D4F958FE
        secret:
          type: string
          example: C275F5EF21169E1F
      required:
        - passphrase
        - secret
  ############ Parameters ############
  parameters:
    token:
      name: token
      in: header
      required: true
      schema:
        type: string
        example: t/UHNNKu6LJX7wQL7iMfZhFZhUZ2IOafzEdfsMEVEAD1kyn3/qhU3LvpTEggqxJyJH03QglCJ3/gEd3oMC12jA==